trigger: 
 branches:
   include:
     - main

variables:
- template: wb-variables.yml

stages:

- stage: wbDeployDev
  displayName: 'DEV Stage'
  jobs:
  - deployment: wbDeployDEV
    environment: DEV
    timeoutInMinutes: 120
    displayName:  'wb Deploy DEV'
    pool: 
      vmImage: windows-latest
    strategy: 
      runOnce:
        deploy:
          steps:
            - template:  'wb-steps.yml'

    variables:
      prefix:  'wbdevne'

- stage: wbDeployQA
  displayName: 'QA Stage'
  jobs:
  - deployment: wbDeployQA
    environment: QA
    timeoutInMinutes: 120
    displayName:  'wb Deploy QA'
    pool: 
      vmImage: windows-latest
    strategy: 
      runOnce:
        deploy:
          steps:
            - template:  'wb-steps.yml'

    variables:
      prefix:  'wbqane'

- stage: wbDeployProd
  displayName: 'Prod Stage'
  jobs:
  - deployment: wbDeployProd
    environment: Prod
    timeoutInMinutes: 120
    displayName:  'wb Deploy Prod'
    pool: 
      vmImage: windows-latest
    strategy: 
      runOnce:
        deploy:
          steps:
            - template:  'wb-steps.yml'

    variables:
      prefix:  'wbprodne'