trigger: 
 branches:
   include:
     - master

variables:
  - template: wb-variables.yml

stages:


- stage: wbDeployDev
  displayName: 'DEV Stage'
  jobs:
  - deployment: wbDeployDEV
    environment: DEV      
    timeoutInMinutes: 120
    displayName:  'wb Deploy DEV'
    pool: 
      vmImage: ubuntu-latest
    strategy: 
      runOnce:
        deploy:
          steps:
            - template:  'wb-steps.yml'

  variables:
    - name: prefix
      value:  'wbdevne'



- stage: wbDeployQA
  displayName: 'QA Stage'
  jobs:
  - deployment: wbDeployQA
    environment: QA
    timeoutInMinutes: 120
    displayName:  'wb Deploy QA'
    pool: 
      vmImage: ubuntu-latest
    strategy: 
      runOnce:
        deploy:
          steps:
            - template:  'wb-steps.yml'

    variables:
      - name: prefix
        value:  'wbqane'


- stage: wbDeployProd
  displayName: 'Prod Stage'
  jobs:
  - deployment: wbDeployProd
    environment: Prod
    timeoutInMinutes: 120
    displayName:  'wb Deploy Prod'
    pool: 
      vmImage: ubuntu-latest
    strategy: 
      runOnce:
        deploy:
          steps:
            - template:  'wb-steps.yml'
              parameters:
                  deployEnvironment: 'dev'

    variables:
      - name: prefix
        value:  'wbprodne'


